### ISSUE TITLE
fix transaction.dataset

### ISSUE THREAD

**Issue by tinguen** [tinguen/DatasetTransaction#1]
```js
const transaction = DatasetTransaction.start(data);
console.log(transaction.dataset); // error
```
Possible cause: getOwnPropertyDescriptor handler

**Comment by tinguen** [comment]
@tshemsedinov

**Comment by tshemsedinov** [comment]
Paste exception message here

**Comment by tinguen** [comment]
@tshemsedinov 
how to catch it:
```js
'use strict';

const DatasetTransaction = require('./dataset.js');

const data = [
  { college: 'MIT', rank: 1},
  { college: 'Oxford', rank: 6},
  { college: 'KPI', rank: 550 },
  { college: 'KNU', rank: Infinity }
];

const transaction = DatasetTransaction.start(data);

console.log(transaction.dataset);
```
error message:
util.js:452
  var symbols = Object.getOwnPropertySymbols(value);
                       ^

TypeError: 'ownKeys' on proxy: trap result did not include 'length'
    at Function.getOwnPropertySymbols (<anonymous>)
    at formatValue (util.js:452:24)
    at inspect (util.js:328:10)
    at format (util.js:195:12)
    at Console.log (console.js:131:21)
    at Object.<anonymous> (/Users/tinguen/Desktop/Coding/Git/DatasetTransaction/issue.js:14:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
